import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Contact,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image as ImageIcon,
  Laptop,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Ticket,
  Trash,
  User,
  X,
  Mail,
  CalendarCheck,
  Lock,
  Loader2 as Spinner,
  Github as GitHub,
  Mail as Google
} from "lucide-react"

export const Icons = {
  alertTriangle: AlertTriangle,
  arrowRight: ArrowRight,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  contact: Contact,
  creditCard: CreditCard,
  file: File,
  fileText: FileText,
  helpCircle: HelpCircle,
  image: ImageIcon,
  laptop: Laptop,
  loader: Loader2,
  login: LogIn,
  moon: Moon,
  moreVertical: MoreVertical,
  pizza: Pizza,
  plus: Plus,
  settings: Settings,
  spinner: Spinner,
  gitHub: GitHub,
  google: Google,
  sun: SunMedium,
  ticket: Ticket,
  trash: Trash,
  user: User,
  x: X,
  mail: Mail,
  calendarCheck: CalendarCheck,
  lock: Lock
}
